
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.cup;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int DIAGONAL = 28;
  public static final int ALINEACION = 39;
  public static final int BORRAR_PAGINA = 14;
  public static final int PAGINA = 16;
  public static final int PARAMETROS = 23;
  public static final int NOMBRE = 24;
  public static final int ANCHO = 43;
  public static final int CORCHETEC = 31;
  public static final int CORCHETEA = 30;
  public static final int ETIQUETAS = 44;
  public static final int VIDEO = 36;
  public static final int MENU = 37;
  public static final int MAYORQUE = 27;
  public static final int IGUAL = 25;
  public static final int TITULO = 10;
  public static final int PADRE = 12;
  public static final int ID = 3;
  public static final int NUEVA_PAGINA = 9;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 19;
  public static final int CLASE = 17;
  public static final int COMILLAS = 29;
  public static final int error = 1;
  public static final int FECHA_MODIFICACION = 6;
  public static final int ATRIBUTOS = 45;
  public static final int ACTION = 33;
  public static final int BORRAR_SITIO_WEB = 8;
  public static final int ATRIBUTO = 32;
  public static final int ACCION = 20;
  public static final int COLOR = 40;
  public static final int MENORQUE = 26;
  public static final int USUARIO_MODIFICACION = 7;
  public static final int FECHA_CREACION = 5;
  public static final int NUEVO_SITIO_WEB = 2;
  public static final int USUARIO_CREACION = 4;
  public static final int IMAGEN = 35;
  public static final int ORIGEN = 41;
  public static final int PARRAFO = 34;
  public static final int MODIFICAR_COMPONENTE = 15;
  public static final int AGREGAR_COMPONENTE = 18;
  public static final int PARAMETRO = 22;
  public static final int ACCIONES = 21;
  public static final int SITIO = 11;
  public static final int TEXTO = 38;
  public static final int ALTURA = 42;
  public static final int MODIFICAR_PAGINA = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUEVO_SITIO_WEB",
  "ID",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "USUARIO_MODIFICACION",
  "BORRAR_SITIO_WEB",
  "NUEVA_PAGINA",
  "TITULO",
  "SITIO",
  "PADRE",
  "MODIFICAR_PAGINA",
  "BORRAR_PAGINA",
  "MODIFICAR_COMPONENTE",
  "PAGINA",
  "CLASE",
  "AGREGAR_COMPONENTE",
  "BORRAR_COMPONENTE",
  "ACCION",
  "ACCIONES",
  "PARAMETRO",
  "PARAMETROS",
  "NOMBRE",
  "IGUAL",
  "MENORQUE",
  "MAYORQUE",
  "DIAGONAL",
  "COMILLAS",
  "CORCHETEA",
  "CORCHETEC",
  "ATRIBUTO",
  "ACTION",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "TEXTO",
  "ALINEACION",
  "COLOR",
  "ORIGEN",
  "ALTURA",
  "ANCHO",
  "ETIQUETAS",
  "ATRIBUTOS"
  };
}

