
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.example.cup;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int DIAGONAL = 26;
  public static final int ALINEACION = 36;
  public static final int BORRAR_PAGINA = 14;
  public static final int PAGINA = 16;
  public static final int PARAMETROS = 21;
  public static final int INITATRIBUTOS = 52;
  public static final int NOMBRE = 22;
  public static final int ENDPARAMETROS = 51;
  public static final int ANCHO = 40;
  public static final int ENDACCIONES = 43;
  public static final int CORCHETEC = 29;
  public static final int ENDPARAMETRO = 47;
  public static final int CORCHETEA = 28;
  public static final int INITACCIONES = 42;
  public static final int ETIQUETAS = 41;
  public static final int VIDEO = 33;
  public static final int MENU = 34;
  public static final int IDENTIFICADOR = 55;
  public static final int MAYORQUE = 25;
  public static final int IGUAL = 23;
  public static final int ENDACCION = 45;
  public static final int INITPARAMETRO = 46;
  public static final int TITULO = 10;
  public static final int PADRE = 12;
  public static final int ID = 3;
  public static final int NUEVA_PAGINA = 9;
  public static final int EOF = 0;
  public static final int BORRAR_COMPONENTE = 19;
  public static final int INITATRIBUT = 48;
  public static final int CLASE = 17;
  public static final int COMILLAS = 27;
  public static final int error = 1;
  public static final int FECHA_MODIFICACION = 6;
  public static final int BORRAR_SITIO_WEB = 8;
  public static final int ATRIBUTO = 30;
  public static final int COLOR = 37;
  public static final int ENDATRIBUT = 49;
  public static final int MENORQUE = 24;
  public static final int USUARIO_MODIFICACION = 7;
  public static final int FECHA_CREACION = 5;
  public static final int NUEVO_SITIO_WEB = 2;
  public static final int USUARIO_CREACION = 4;
  public static final int IMAGEN = 32;
  public static final int ORIGEN = 38;
  public static final int PARRAFO = 31;
  public static final int MODIFICAR_COMPONENTE = 15;
  public static final int AGREGAR_COMPONENTE = 18;
  public static final int HEXADECIMAL = 54;
  public static final int PARAMETRO = 20;
  public static final int SITIO = 11;
  public static final int TEXTO = 35;
  public static final int ALTURA = 39;
  public static final int ENDATRIBUTOS = 53;
  public static final int INITACCION = 44;
  public static final int MODIFICAR_PAGINA = 13;
  public static final int INITPARAMETROS = 50;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUEVO_SITIO_WEB",
  "ID",
  "USUARIO_CREACION",
  "FECHA_CREACION",
  "FECHA_MODIFICACION",
  "USUARIO_MODIFICACION",
  "BORRAR_SITIO_WEB",
  "NUEVA_PAGINA",
  "TITULO",
  "SITIO",
  "PADRE",
  "MODIFICAR_PAGINA",
  "BORRAR_PAGINA",
  "MODIFICAR_COMPONENTE",
  "PAGINA",
  "CLASE",
  "AGREGAR_COMPONENTE",
  "BORRAR_COMPONENTE",
  "PARAMETRO",
  "PARAMETROS",
  "NOMBRE",
  "IGUAL",
  "MENORQUE",
  "MAYORQUE",
  "DIAGONAL",
  "COMILLAS",
  "CORCHETEA",
  "CORCHETEC",
  "ATRIBUTO",
  "PARRAFO",
  "IMAGEN",
  "VIDEO",
  "MENU",
  "TEXTO",
  "ALINEACION",
  "COLOR",
  "ORIGEN",
  "ALTURA",
  "ANCHO",
  "ETIQUETAS",
  "INITACCIONES",
  "ENDACCIONES",
  "INITACCION",
  "ENDACCION",
  "INITPARAMETRO",
  "ENDPARAMETRO",
  "INITATRIBUT",
  "ENDATRIBUT",
  "INITPARAMETROS",
  "ENDPARAMETROS",
  "INITATRIBUTOS",
  "ENDATRIBUTOS",
  "HEXADECIMAL",
  "IDENTIFICADOR"
  };
}

